name: mintsafe_wallet
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.1
  get: ^4.6.5
  scaffold_gradient_background: ^1.0.3+1

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/poppin/Poppins-Bold.ttf
        - asset: asset/font/poppin/Poppins-SemiBold.ttf
        - asset: asset/font/poppin/Poppins-Medium.ttf
        - asset: asset/font/poppin/Poppins-Regular.ttf
        - asset: asset/font/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: asset/font/roboto/Roboto-Bold.ttf
        - asset: asset/font/roboto/Roboto-Medium.ttf
        - asset: asset/font/roboto/Roboto-Regular.ttf
        - asset: asset/font/roboto/Roboto-Light.ttf
