name: mintsafe_wallet
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip39: ^1.0.6
  blockies_ethereum: ^0.0.2
  collection: ^1.17.1
  connectivity_checker: ^1.1.0
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  dart_bip32_bip44: ^0.2.0
  dio: ^5.3.2
  encrypt: ^5.0.1
  erc20: ^1.0.1
  eth_abi_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-abi-codec.git
      ref: 2.0.0
  eth_sig_util: ^0.0.9
  ethereum_addresses: ^1.0.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_polygon: ^0.3.0+2
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.8.1
  flutter_switch: ^0.3.2
  get: ^4.6.5
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  mobile_scanner: ^3.2.0
  number_system: ^0.0.6+8
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  wallet_connect: ^1.0.4
  web3_provider: ^1.1.4
  web3dart: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/icon/
    - asset/abi/ERC-20.json
    - asset/abi/chain.json

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/poppin/Poppins-Bold.ttf
        - asset: asset/font/poppin/Poppins-SemiBold.ttf
        - asset: asset/font/poppin/Poppins-Medium.ttf
        - asset: asset/font/poppin/Poppins-Regular.ttf
        - asset: asset/font/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: asset/font/roboto/Roboto-Bold.ttf
        - asset: asset/font/roboto/Roboto-Medium.ttf
        - asset: asset/font/roboto/Roboto-Regular.ttf
        - asset: asset/font/roboto/Roboto-Light.ttf
