name: mintsafe_wallet
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip39: ^1.0.6
  blockies_ethereum: ^0.0.2
  build_runner: ^2.4.6
  collection: ^1.17.1
  connectivity_checker: ^1.1.0
  connectivity_plus: ^5.0.1
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  dart_bip32_bip44: ^0.2.0
  encrypt: ^5.0.1
  erc20: ^1.0.1
  eth_abi_codec:
    git:
      url: https://github.com/nbltrust/dart-eth-abi-codec.git
      ref: 2.0.0
  eth_sig_util: ^0.0.9
  ethereum_addresses: ^1.0.2
  ffcache: ^1.1.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_polygon: ^0.3.0+2
  flutter_screenutil: ^5.8.1
  flutter_slidable: ^3.0.1
  flutter_switch: ^0.3.2
  get: ^4.6.5
  http: ^0.13.5
  in_app_update: ^4.2.2
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  loading_overlay: ^0.3.0
  mobile_scanner: ^3.2.0
  number_system: ^0.0.6+8
  package_info_plus: ^4.2.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.1
  skeletonizer: ^0.8.0
  url_launcher: ^6.1.11
  wallet_connect: ^1.0.4
  web3_provider: ^1.1.4
  web3dart: ^2.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/icon/
    - asset/abi/chain.json
    - asset/abi/ERC-20.json
    - asset/abi/ERC-721.json
    - asset/abi/token.json
    - asset/logo/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/poppin/Poppins-Bold.ttf
        - asset: asset/font/poppin/Poppins-SemiBold.ttf
        - asset: asset/font/poppin/Poppins-Medium.ttf
        - asset: asset/font/poppin/Poppins-Regular.ttf
        - asset: asset/font/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: asset/font/roboto/Roboto-Bold.ttf
        - asset: asset/font/roboto/Roboto-Medium.ttf
        - asset: asset/font/roboto/Roboto-Regular.ttf
        - asset: asset/font/roboto/Roboto-Light.ttf
